# Contesto {#contesto}

Be aware that this documentation is currently under development.

## Contesto del Progetto 

L’Alta Scuola di Economia e Management dei Sistemi Sanitari (**<span style="color:#ee943a">ALTEMS</span>**) della Facoltà di Economia in collaborazione con il Dipartimento di Scienze della Vita e Sanità Pubblica (Sezione di Igiene)
della Facoltà di Medicina e Chirurgia diffonde settimanalmente l’Instant Report COVID-19, un’iniziativa che offre un confronto sistematico delle modalità di risposta delle Regioni italiane al Sars-COV-2. Il Report si basa su un set di indicatori costruito per monitorare l’evoluzione della pandemia nella “Fase 2”, formalmente avviata il 4 maggio con la conclusione del lockdown nazionale. Al fianco dei nuovi indicatori, il Rapporto continua ad offrire l’aggiornamento di alcuni indicatori selezionati tra quelli che hanno caratterizzato il modello di risposta delle Regioni nella fase 1. L’analisi riguarda tutte le 21 Regioni e Province Autonome italiane.


## Gruppo di Lavoro ALTEMS

Il gruppo di lavoro è coordinato da **Americo Cicchetti**, Professore Ordinario di Organizzazione Aziendale presso la Facoltà di Economia dell’Università Cattolica del Sacro Cuore si avvale della advisorship scientifica del Prof. **Gianfranco Damiani** e della Dott.ssa **Maria Lucia Specchia** della Sezione di Igiene - Dipartimento di Scienze della Vita e Sanità Pubblica. A partire dal Report #4 la collaborazione si è estesa al Centro di Ricerca e Studi in Management Sanitario dell’Università Cattolica (Prof. **Eugenio Anessi Pessina**), al Centro di Ricerca e Studi sulla Leadership in Medicina dell’Università Cattolica (Prof. **Walter Ricciardi**) e al Gruppo di Organizzazione dell’Università Magna Græcia di Catanzaro (Prof. **Rocco Reina**). Il team multidisciplinare è composto da economisti e aziendalisti sanitari, medici di sanità pubblica, ingegneri informatici, psicologi e statistici.



## Finalità e Proposta

La finalità è comprendere le implicazioni delle diverse strategie adottate dalle Regioni per fronteggiare la diffusione del virus e le conseguenze del Covid-19 in contesti diversi per trarne indicazioni per il futuro prossimo e per acquisire insegnamenti derivanti da questa drammatica esperienza.


In linea con gli obiettivi sopra descritti, l’associazione **<span style="color:#5d3bff">Data Network</span>** propone il suo supporto nel curare e valorizzare il ruolo dei dati all’interno del progetto, convinta che l’ampia gamma di dati aperti (open data) a disposizione nel settore pubblico-sanitario e la conseguente possibilità di riutilizzo degli stessi possa consentire di sfruttarne il potenziale e contribuire allo sviluppo economico nonchè ad importanti obiettivi sociali quali la responsabilizzazione e la trasparenza. Forte di avere a disposizione un gruppo di soci con esperienze e competenze eterogenee. Data Network ritiene di poter offrire un contributo qualificato a supporto della prosecuzione delle iniziative di **<span style="color:#ee943a">ALTEMS</span>**) mettendo a disposizione professionalità con una consolidata esperienza sulle tematiche oggetto della proposta.



