# Indicatore Zona Gialla

Il presente step ha l’obiettivo di analizzare il lavoro svolto attualmente per la produzione
della reportistica, prendendo in considerazione **sorgenti dati**, strumenti di manipolazione dati
utilizzati e caratteristiche di visualizzazione. 

## Roadstart

Dopo questa fase iniziale sarà possibile valutare nuovi strumenti e servizi per ottimizzare la lavorazione. Inoltre, verrà creato un indicatore di stress per adeguare le soglie di incidenza covid ai risultati delle campagne vaccinali regionali. L’indice finale riuscirà a combinare congiuntamente l’effetto dei vaccini e dell’aumento dei contagi tenendo conto della popolazione suscettibile. Il progetto consisterà nel produrre un codice per il calcolo dell’indicatore (rilasciato in open source) e un’estensiva documentazione per il riutilizzo. Il nuovo indicatore verrà affiancato al monitoraggio degli indicatori fondamentali per stabilire il passaggio tra i colori delle regioni: incidenza settimanale, tasso di saturazione dei posti letto covid e terapie intensive.
