# # Hourly scraping
# name: refresh_data
# 
# #  Controls when the action will run.
# #  “At minute 0 past every 3rd hour.”
# #  https://crontab.guru/
# #  On push for testin purpose
# on:
#   push:
#     branches: dev
#   # schedule:
#   #   - cron:  '0 */3 * * *'
# 
# 
# jobs: 
#   etl:
#     # The type of runner that the job will run on
#     runs-on: macos-latest
# 
#     # Load repo and install R
#     steps:
#     - uses: actions/checkout@master
#     - uses: r-lib/actions/setup-r@master
# 
#     # Set-up R
#     - name: Install packages
#       run: |
#         R -e 'install.packages("dplyr")'
#         R -e 'install.packages("stringr")'
#         R -e 'install.packages("readr")'
#         R -e 'install.packages("readxl")'
#         R -e 'install.packages("timetk")'
#         R -e 'install.packages("writexl")'
#         R -e 'install.packages("lubridate")'
#         R -e 'install.packages("here")'
#         R -e 'install.packages("writexl")'
#         
# # Run pipeline
#     - name: Run Pipeline
#       run: Rscript code_dev.R
# 
#     # Commit new files
#     - name: Commit files
#       run: |
#         git config --local user.name github-actions
#         git config --local user.email "actions@github.com"
#         git add data/*
#         git commit -am "GH ACTION Autorun $(date)"
#         git push origin dev
#       env:
#         REPO_KEY: ${{secrets.GITHUB_TOKEN}}
#         username: github-actions
